### ISSUE TITLE
Using images as input for lighting

### ISSUE THREAD

**Issue by leonardodora** [semagnum/light-painter#35]
hi. What should I do if I want to use a portrait as input instead of 3d model in blender?

**Comment by leonardodora** [comment]
> Hi! Using images as input isn't supported in Light Painter. I'll consider a compositor feature for the backlog when I have time.
> 
> But in the meantime, you do have options. If you don't have a normal map, you can bake one in Blender by adding depth and curves with displacement or AI (perhaps like this one: [imageamigo.com/photodepth/](https://imageamigo.com/photodepth/)). Once you have a normal pass of your image, you can relight in a compositor like Blender or Photoshop: https://youtu.be/cSSwERDRN7k
> 
> The paid version of Davinci Resolve has an option to do this now with Relight FX.[blackmagicdesign.com/products/davinciresolve/whatsnew](https://www.blackmagicdesign.com/products/davinciresolve/whatsnew)

thanks for your reply, I'll check them out!

**Comment by semagnum** [comment]
Unfortunately, Blender's compositor has very few vector nodes (no vector math!), so this may need to be done in a hacky fashion with the shader editor or just in a different software. So, I'll put this as a won't fix, at least until there's good vector node support in the compositor.

**Comment by semagnum** [comment]
Blender's compositor still hasn't added any of the required functionality for this, so will close this. And probably would be worth as a separate add-on.
