### ISSUE TITLE
An error is reported when adding a plug-in

### ISSUE THREAD

**Issue by Gilgamesh-Plan** [semagnum/light-painter#71]
Tool 'view3d.lightpaint_lamp' already exists!
register_class(...): already registered as a subclass 'LIGHTPAINTER_OT_Lamp'
How to fix the inability to start the plugin

**Comment by semagnum** [comment]
Is this only happening after an update or is the first installation of it? From the extensions platform or from manually installing the .zip file all together? Does restarting Blender fix it? You could also check the folder where all the add-ons are installed (it should show the add-ons' filepath in the add-ons tab, go one folder above that), see if it's there twice.

While the error message is helpful, it's not enough for me to reproduce on my end. And the code only registers it once, so I'm wondering if you have a previous version still in there. In which case, you need to uninstall the old version _and_ restart Blender before installing the new one.

**Comment by semagnum** [comment]
Since you have not responded with steps to reproduce the issue, and no one else has corroborated the issue, will close.
